=== washingtonpost/ans-schema/src/main/resources/schema/ans/0.8.0/audio.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/audio.json",
  "description": "Audio Content",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "type": {
      "type": "string",
      "enum": [ "audio" ]
    },

    "_id": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_id.json"
    },
    "version": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_version.json"
    },
    "subtype": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_subtype.json"
    },
    "channels": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_channel.json"
    },
    "alignment": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_alignment.json"
    },

    "language": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_locale.json"
    },
    "copyright": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_copyright.json"
    },
    "canonical_url": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_canonical_url.json"
    },
    "short_url": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_short_url.json"
    },
    "created_date": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_created_date.json"
    },
    "last_updated_date": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_last_updated_date.json"
    },
    "publish_date": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_publish_date.json"
    },
    "first_publish_date": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_first_publish_date.json"
    },
    "display_date": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_display_date.json"
    },
    "location": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_location.json"
    },
    "geo": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_geo.json"
    },
    "address": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_address.json"
    },
    "editor_note": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_editor_note.json"
    },
    "status": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_status.json"
    },
    "headlines": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_headlines.json"
    },
    "subheadlines": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_subheadlines.json"
    },
    "description": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_description.json"
    },
    "credits": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_credits.json"
    },
    "taxonomy": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_taxonomy.json"
    },
    "promo_items": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_promo_items.json"
    },
    "related_content": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_related_content.json"
    },
    "owner": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_owner.json"
    },
    "planning": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_planning.json"
    },
    "workflow": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_workflow.json"
    },
    "pitches": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_pitches.json"
    },
    "revision": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_revision.json"
    },
    "syndication": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_syndication.json"
    },
    "source": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_source.json"
    },
    "distributor": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_distributor.json"
    },
    "tracking": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_tracking.json"
    },
    "comments": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_comments.json"
    },
    "label": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_label.json"
    },
    "slug": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_slug.json"
    },
    "content_restrictions": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_content_restrictions.json"
    },

    "additional_properties": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_additional_properties.json"
    },

    "content_aliases": {
      "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/traits/trait_content_aliases.json"
    },


    "source_url": {
      "description": "(Deprecated.) The audio source file. Use 'streams' instead.",
      "type": "string"
    },
    "mimetype": {
      "description": "(Deprecated.) Mime type of audio source file. Use 'streams' instead.",
      "type": "string"
    },
    "autoplay": {
      "description": "Whether to autoplay is enabled.",
      "type": "boolean"
    },
    "controls": {
      "description": "Whether controls are enabled.",
      "type": "boolean"
    },
    "loop": {
      "description": "Whether looping is enabled.",
      "type": "boolean"
    },
    "preload": {
      "description": "Whether preload is enabled.",
      "type": "boolean"
    },

    "streams": {
      "description": "The different streams this audio can play in.",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "https://raw.githubusercontent.com/washingtonpost/ans-schema/master/src/main/resources/schema/ans/0.8.0/utils/audio_stream.json"
      }
    }
  },
  "required": [ "type", "version" ],
  "oneOf": [{
    "required": [ "streams" ]
  }, {
    "required": [ "source_url" ]
  }]
}

=== washingtonpost/ans-schema/tests/fixtures/schema/0.10.5/audio-fixture-good.json
{
  "_id": "0987654321",
  "type": "audio",
  "version": "0.10.5",
  "source_url": "https://www.washingtonpost.com/audio/foo/bar.mp3",
  "mimetype": "audio/mp3",
  "credits": {
    "by": [
      {
        "type": "author",
        "version": "0.10.5",
        "name": "John Jacob",
        "byline": "John Jacob"
      }
    ]
  },
  "additional_properties": {
    "foo": "bar"
  }
}
